#pragma once
#include "Entity_component_sys.h"
#include "TransformComponent.h"
#include "SpriteComponent.h"
#include "Controller.h"
#include "Collider_component.h"
#include "Tile_component.h"
#include "Projectile_component.h"
#include "UI_label.h"